# Generated by Django 5.2.17 on 2026-09-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('spending_limit', 'Spending Limit'), ('max_single_order', 'Max Single Order'), ('category_approval', 'Category Approval')], max_length=30)),
                ('scope', models.CharField(default='global', help_text='"global" or a specific user_id as a string', max_length=50)),
                ('threshold_paise', models.IntegerField(help_text='Threshold in paise (1 INR = 100 paise)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Extra parameters (e.g. category name)')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rule_type'],
            },
        ),
    ]
